name: vuex4flutter
description: Vuex4Flutter is a state management pattern that provides a VueX like interface. Super lightweight and more important, testable!
version: 0.0.2-dev
homepage: https://github.com/hjJunior/vuex4flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  get_it: ^4.0.1
  rxdart: ^0.23.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
